apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  releaseName: postgres
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: postgres
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  values:
    auth:
      postgresPassword: password
      username: charles
      password: password
    global:
      postgresql:
        auth:
          postgresPassword: password
