apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  chart:
    spec:
      version: ">=15.5.17"
  test:
    enable: false
  values:
    global:
      postgresql:
        auth:
          postgresPassword: password-staging